title: "S Garrett"
email: quitesadgeese@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a portfolio for storing CV material and have a laugh until the graceful hand of death shall claim my already frail body. 
  Or until I get bored... [please edit this]
# Root directory for your portfolio. On GitHub Pages, this is the name of your repository.
baseurl: "/legendary-octo-lamp"
# Protocol + hostname for your portfolio. On GitHub Pages, this is https://yourusername.github.io
url: "https://heftygolfish31.github.io" 
twitter_username: mlhacks
github_username: heftygolfish31
form_url: "https://formspree.io/f/xrgodpqo"
social_image: "./assets/img/social-link.jpg"
social_image_alt: # Alt text for the link preview image
google_analytics_measurement_id: # G-XXXXXXXXXX

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
